# pre-commit run --all-files
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==21.6b0]
  # Disable flakehell for now due to import bug with newer flake8
  # https://github.com/flakehell/flakehell/issues/22
  # - repo: https://github.com/flakehell/flakehell
  #   rev: v.0.9.0
  #   hooks:
  #     - name: Run flakehell static analysis tool
  #       id: flakehell
