name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: false
          virtualenvs-in-project: true

      - name: Load cached venvs
        id: cached-venvs
        uses: actions/cache@v2
        with:
          path: |
            .venv
            .tox
          key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

			- name: Run tests
				run: make lint
