name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  create-venv:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: false
          virtualenvs-in-project: true

      - name: Restore cached venv
        uses: syphar/restore-virtualenv@v1
        id: cache-venv

      - name: Restore Pip download cache
        uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Install Python dependencies
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: make python-install-deps PY_INSTALL_ARGS="--extras=docs"

  lint:
    name: Lint
    needs: create-venv
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: false
          virtualenvs-in-project: true

      - name: Restore cached venv
        uses: syphar/restore-virtualenv@v1
        id: cache-venv

      - name: Run linting tools
        run: make lint lint-docs

  build:
    name: Build
    needs: create-venv
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: false
          virtualenvs-in-project: true

      - name: Restore cache venv
        uses: syphar/restore-virtualenv@v1
        id: cache-venv

      - name: Build package
        run: make build

  test:
    name: Test
    needs: create-venv
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: false
          virtualenvs-in-project: true

      - name: Restore cache venv
        uses: syphar/restore-virtualenv@v1
        id: cache-venv

      - name: Run tests
        run: make test

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          virtualenvs-create: false
          virtualenvs-in-project: true

      - name: Restore cache venv
        uses: syphar/restore-virtualenv@v1
        id: cache-venv

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1.0.3
        with:
          languages: python
          setup_python_dependencies: false

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1.0.3
